---
title: "Rscript_Yadav2023_Merge4Patients"
author: "Victor Gaya"
date: "`r Sys.Date()`"
output: html_document
---

Loading required packages

```{r}
#| label: packages
# Load essential libraries for Seurat, data visualization, and manipulation
library(Seurat)
library(SeuratData)
library(SeuratObject)
library(ggplot2)
library(patchwork)
library(dplyr)

# Libraries for embedding tools and HTML content
library("htmltools")
library("vembedr")

# Bioconductor manager and hdf5 file handling
library(BiocManager)
library(glmGamPoi)
library(hdf5r)

# Set a higher memory limit to handle large datasets
options(future.globals.maxSize = 8000 * 1024^2)
```

Defining input and output directories

```{r}
#| label: files1
# Define the folder where raw data is located
inputDir <- "/Users/vagm_110901/Documents/Universitat/ConesaLab/Lab/02.Seurat/Yadav2023_adult_human_spinal_cord/data/GSE222322_RAW"

# Define the folder where output images or results will be saved
saveDir <- "/Users/vagm_110901/Documents/Universitat/ConesaLab/Lab/02.Seurat/Yadav2023_adult_human_spinal_cord/ImagenesYadavMergeSlices"
```

Listing directories and files for each sample

```{r}
#| label: files2
# List all subdirectories in the input folder
subdirectories <- list.dirs(path = inputDir, full.names = TRUE, recursive = FALSE)

# For each subdirectory, list the files within it
files_per_directory <- lapply(subdirectories, function(subdir) list.files(path = subdir, full.names = TRUE))
```

Creating Seurat objects for each sample (without normalization)

```{r}
#| label: SeuratObjects1
# Create an empty list to store the Seurat objects
h5_seurat <- list()

# Initialize counters to keep track of slices for each patient
num19 <- 0; num43 <- 0; num47 <- 0; num45 <- 0

# Loop through each subdirectory to process the files
for (i in seq_along(subdirectories)) {
  
  # Extract the slice name from the folder path
  slice_name <- tail(strsplit(subdirectories[[i]], "/")[[1]], 1)
  
  # Extract the HDF5 file name from the listed files
  h5_filename <- tail(strsplit(files_per_directory[[i]], "/")[[1]], 1)
  
  # Load the spatial data for each sample using the Load10X_Spatial function
  sample_obj <- Load10X_Spatial(data.dir = subdirectories[i], 
                                filename = h5_filename, 
                                assay = "Spatial",
                                filter.matrix = TRUE, 
                                to.upper = FALSE)
  
  # Assign each sample to a specific patient based on the slice name
  if (substr(slice_name, 26, 30) == "02636") { 
    patient <- "paciente19"
    num19 <- num19 + 1 
    sample_obj@meta.data$name <- paste0("slice19_", num19)
  } else if (substr(slice_name, 26, 30) == "00022") { 
    patient <- "paciente43"
    num43 <- num43 + 1
    sample_obj@meta.data$name <- paste0("slice43_", num43)
  } else if (substr(slice_name, 26, 30) == "00023") { 
    patient <- "paciente47"
    num47 <- num47 + 1
    sample_obj@meta.data$name <- paste0("slice47_", num47)
  } else if (substr(slice_name, 26, 30) == "00025") { 
    patient <- "paciente45"
    num45 <- num45 + 1
    sample_obj@meta.data$name <- paste0("slice45_", num45)
  }
  
  # Add patient information to the Seurat object's metadata
  sample_info <- sample(x = patient, size = ncol(x = sample_obj), replace = TRUE)
  sample_obj$info <- sample_info
  
  # Fix a potential bug where coordinates are saved as characters instead of integers
  sample_obj@images$slice1@coordinates[] <- lapply(sample_obj@images$slice1@coordinates, as.integer)
  
  # Add a custom feature representing the percentage of cells expressing certain genes
  sample_obj[["percent.butterfly"]] <- PercentageFeatureSet(sample_obj, features = c("SNAP25", "MAP2", "RBFOX3", "SYP"))
  
  # Append the processed Seurat object to the list
  h5_seurat <- append(h5_seurat, sample_obj)
}
```


Creating a list for the mix of patients

```{r}
#| label: pacienteMIX.list
# Create an empty list to store the selected samples
pacienteMIX.list <- list()

# Vector containing the names of the patients we want to select
pacientes <- c("paciente19", "paciente43", "paciente47", "paciente45")

# Counter to iterate over the patients
N <- 1

# Iterate over elements in h5_seurat
for (elem in h5_seurat) {
  # If the current patient matches the patient in position N of the 'pacientes' vector
  if (elem$info[[1]] == pacientes[N]) {
    # Add the Seurat object to the list
    pacienteMIX.list <- append(pacienteMIX.list, elem)
    # Increment the counter to move to the next patient
    N <- N + 1
  }
  # Break the loop if 4 samples have already been selected
  if (N > length(pacientes)) break
}
```

Plotting violin plots for each slice of mix of patients

```{r}
#| label: pacienteMIX.list_plot
# Loop through each Seurat object and create violin plots for specific features
for (i in 1:length(pacienteMIX.list)) {
  p <- VlnPlot(
    pacienteMIX.list[[i]], 
    features = c("nFeature_Spatial", "nCount_Spatial", "percent.butterfly"), 
    pt.size = 0.1, ncol = 3
  ) & 
  theme(
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
  )
  
  # Print the plots
  print(p)
}
```

############################################################################### Merge Only

```{r}
#| label: pacienteMIX_Merge
# Create unique identifiers for each slice
slice_ids <- c()
for (i in seq_along(pacienteMIX.list)) { 
  slice_ids <- c(slice_ids, paste0("slice_", i)) 
}

# Merge all slices from MIX of patients into a single Seurat object
pacienteMIX.merge  <- merge(x = pacienteMIX.list[[1]], 
                           y = pacienteMIX.list[2:length(pacienteMIX.list)], 
                           add.cell.ids = slice_ids, 
                           project = "VisiumPacienteMIX")

# Rename the first slice in the merged object to avoid duplication issues
names(pacienteMIX.merge@images)[1] <- "slice1.1"
```

```{r}
#| label: pacienteMIX_save
# Save the merged Seurat object as an RDS file
saveRDS(pacienteMIX.merge, file = paste0(saveDir, "/PacienteMIX_merge.rds"))

# Load the merged Seurat object from the RDS file
pacienteMIX.merge <- readRDS(file = paste0(saveDir, "/PacienteMIX_merge.rds"))
```

```{r}
#| label: pacienteMIX_visualize
# Plot spatial dimensions of the merged object with reduced opacity
SpatialDimPlot(pacienteMIX.merge, alpha = 0.5, crop = FALSE, ncol = 2)

# Plot spatial expression of the "percent.butterfly" feature
SpatialPlot(object = pacienteMIX.merge, 
            features = "percent.butterfly", alpha = 1, crop = FALSE, ncol = 2) & 
  theme(legend.position = "none")
```

