---
title: "Rscript_Yadav2023_scRNAseq"
author: "Victor Gaya"
date: "`r Sys.Date()`"
output: html_document
---

packages
```{r}
library(dplyr)
library(Seurat)
library(patchwork)

library(ggplot2)
library(sctransform)

#library(SeuratData)

options(future.globals.maxSize = 100000 * 1024^2)
```

folders
```{r}
# Define the files folders 
carpetaData <- "/Users/vagm_110901/Documents/Universitat/ConesaLab/Lab/02.Seurat/Yadav2023_adult_human_spinal_cord/data"
saveDir <- "/Users/vagm_110901/Documents/Universitat/ConesaLab/Lab/02.Seurat/Yadav2023_adult_human_spinal_cord/snRNAseq_results"
```

TUTORIAL
```{r}
pbmc.data <- Read10X(data.dir = paste0(carpetaData,"/tutorialSeurat_scRNA/filtered_gene_bc_matrices/hg19/"))

pbmc <- CreateSeuratObject(counts = pbmc.data, project = "pbmc3k", min.cells = 3, min.features = 200)
pbmc

pbmc.data[c("CD3D", "TCL1A", "MS4A1"), 1:30]

pbmc[["percent.mt"]] <- PercentageFeatureSet(pbmc, pattern = "^MT-")

pbmc <- SCTransform(pbmc, vars.to.regress = "percent.mt", verbose = FALSE)

VlnPlot(pbmc, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
```

YADAV DATA
```{r}
filesList <- list.files(path = paste0(carpetaData, "/snRNAseq"), full.names = TRUE)

sn_samples <- list()
n <- 0
for (file in filesList) {
  n <- n + 1
  spinalCord.data <- Read10X_h5(file)
  spinalCord <- CreateSeuratObject(counts = spinalCord.data, project = paste0("sample_",n), 
                                   min.features = 1, min.cells = 1)
  
  # Pre-processing
  spinalCord[["percent.mt"]] <- PercentageFeatureSet(spinalCord, pattern = "^MT-")
  
  print(head(spinalCord@meta.data, 20))
  print(VlnPlot(spinalCord, features = c("nFeature_RNA", "nCount_RNA"), ncol = 3))
  
  # filtered with an nUMI cutoff of >1000
  # nuclei with less than 5% mitochondrial gene contamination were retained
  spinalCord.subset <- subset(spinalCord, subset = nCount_RNA > 1000 & percent.mt < 5)
  print(VlnPlot(spinalCord.subset, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3))
  
  # mitochondrial genes were also removed from the matrices
  mito.genes <- grep("^MT-", rownames(spinalCord.subset), value = TRUE)
  
  spinalCord.subset <- spinalCord.subset[!rownames(spinalCord.subset) %in% mito.genes, ]
  print(sum(rownames(spinalCord.subset) %in% mito.genes))
  
  sn_samples <- append(sn_samples, spinalCord.subset)
}

```

```{r}
saveRDS(sn_samples, paste0(saveDir, "/snRNA_samples.rds"))
```

SCTransform normalization
```{r}
sn_norm <- list()

for (i in 1:length(sn_samples)) {
  file <- SCTransform(sn_samples[[i]])
  
  sn_norm <- append(sn_norm, file)
}
```

```{r}
saveRDS(sn_norm, paste0(saveDir, "/snRNA_normSCT.rds"))
```
```{r}
sn_norm <- readRDS(paste0(saveDir, "/snRNA_normSCT.rds"))
```


CCA based integration
```{r}
# First, we need to specify that we want to use all of the 3000 most variable genes identified by SCTransform for the integration. By default, this function only selects the top 2000 genes.
integ_features <- SelectIntegrationFeatures(object.list = sn_norm, 
                                            nfeatures = 3000) 
```

```{r}
saveRDS(integ_features, paste0(saveDir, "/snRNA_integ_features.rds"))
```
```{r}
integ_features <- readRDS(paste0(saveDir, "/snRNA_integ_features.rds"))
```

```{r}
# we need to prepare the SCTransform object for integration.
sn_norm <- PrepSCTIntegration(object.list = sn_norm, 
                              anchor.features = integ_features)
```


```{r}
saveRDS(sn_norm, paste0(saveDir, "/snRNA_normSCT.rds"))
```
```{r}
sn_norm <- readRDS(paste0(saveDir, "/snRNA_normSCT.rds"))
```


```{r}
# we are going to perform CCA, find the best buddies or anchors and filter incorrect anchors.
integ_anchors <- FindIntegrationAnchors(object.list = sn_norm, 
                                        normalization.method = "SCT", 
                                        anchor.features = integ_features,
                                        reduction = "cca")
```

```{r}
saveRDS(integ_anchors, paste0(saveDir, "/snRNA_integ_anchors.rds"))
```
```{r}
integ_anchors <- readRDS(paste0(saveDir, "/snRNA_integ_anchors.rds"))
```

```{r}
# we can integrate across samples
sn_integrated <- IntegrateData(anchorset = integ_anchors, 
                               normalization.method = "SCT")
```

```{r}
# Run PCA
sn_integrated <- RunPCA(object = sn_integrated)
```

```{r}
saveRDS(sn_integrated, paste0(saveDir, "/snRNA_integratedCCA.rds"))
```
```{r}
sn_integrated <- readRDS(paste0(saveDir, "/snRNA_integratedCCA.rds"))
```

```{r}
# Plot PCA
print(DimPlot(sn_integrated, reduction = "pca"))
print(ElbowPlot(sn_integrated))
print(DimHeatmap(sn_integrated, dims = 1:15, cells = 500, balanced = TRUE))
```

```{r}
saveRDS(sn_integrated, paste0(saveDir, "/snRNA_integratedCCA.rds"))
```
```{r}
sn_integrated <- readRDS(paste0(saveDir, "/snRNA_integratedCCA.rds"))
```

Clustering
```{r}
sn_integrated <- FindNeighbors(sn_integrated, dims = 1:30)
sn_integrated <- FindClusters(sn_integrated, resolution = 0.6)
```

UMAP reduction
```{r}
# Run UMAP
sn_integrated <- RunUMAP(sn_integrated, 
                         dims = 1:30,
			                   reduction = "pca")
```
```{r}
# Plot UMAP                             
p1 <- DimPlot(sn_integrated, reduction = "umap")
print(p1)
ggsave(paste0(saveDir, "/UMAP_snRNA_Yadav.png"), plot = p1)
```

```{r}
# Plot UMAP                             
p1 <- DimPlot(sn_integrated, reduction = "umap", group.by = "orig.ident")
p2 <- DimPlot(sn_integrated, reduction = "umap", group.by = "orig.ident", split.by = "orig.ident", ncol = 4)
print(p1)
print(p2)
ggsave(paste0(saveDir, "/UMAP_snRNA_Yadav_samplesALL.png"), plot = p1)
ggsave(paste0(saveDir, "/UMAP_snRNA_Yadav_samples.png"), plot = p2)

```

Annotation
```{r}
# dictionary with cell types
celltypes <- list(c("SYP","SNAP25","RBFOX3"), c("GFAP","FGFR3"), c("PTPRC","CSF1R","CTSS"), c("MAG","MOG","MOBP","PLP1"), c("OLIG1","VCAN"), c("FLT1","PECAM1"), c("PDGFRB"), c("DCN","COL1A2","ITGA10"), c("MPZ","PMP22"), c("CD247"))
cellnames <- c("neurons", "astrocytes", "microglia", "oligodendrocytes", "OPCs", "endothelial cells", "pericytes", "meningeal cells", "Schwann cells", "lymphocytes")
names(celltypes) <- cellnames
```

integrated assay

```{r}
# Dotplot to asign each cluster a cell type based on the expressed marker genes
# integrated assay
p1 <- DotPlot(sn_integrated, features = celltypes, assay = "integrated") + RotatedAxis() + theme(axis.text.x = element_text(size = 6), axis.text.y = element_text(size = 6), strip.text = element_text(size = 6, angle = 90))
print(p1)
ggsave(paste0(saveDir, "/dotplot_snRNA_Yadav.png"), plot = p1)
```

```{r}
# Classification
sn_integrated@meta.data[,"cell.types"] <- NA

# 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
# 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25

sn_integrated@meta.data[which(sn_integrated@meta.data$seurat_clusters == 19 |
                              sn_integrated@meta.data$seurat_clusters == 18 |
                              sn_integrated@meta.data$seurat_clusters == 15 |
                              sn_integrated@meta.data$seurat_clusters == 14 |
                              sn_integrated@meta.data$seurat_clusters == 12 |
                              sn_integrated@meta.data$seurat_clusters == 1 |
                              sn_integrated@meta.data$seurat_clusters == 0),"cell.types"] <- "neurons"
sn_integrated@meta.data[which(sn_integrated@meta.data$seurat_clusters == 16 |
                              sn_integrated@meta.data$seurat_clusters == 13 |
                              sn_integrated@meta.data$seurat_clusters == 6),"cell.types"] <- "astrocytes"
sn_integrated@meta.data[which(sn_integrated@meta.data$seurat_clusters == 23 |
                              sn_integrated@meta.data$seurat_clusters == 8 |
                              sn_integrated@meta.data$seurat_clusters == 5),"cell.types"] <- "microglia"
sn_integrated@meta.data[which(sn_integrated@meta.data$seurat_clusters == 20 |
                              sn_integrated@meta.data$seurat_clusters == 11 |
                              sn_integrated@meta.data$seurat_clusters == 9 |
                              sn_integrated@meta.data$seurat_clusters == 7 |
                              sn_integrated@meta.data$seurat_clusters == 4 |
                              sn_integrated@meta.data$seurat_clusters == 3 |
                              sn_integrated@meta.data$seurat_clusters == 2),"cell.types"] <- "oligodendrocytes"
sn_integrated@meta.data[which(sn_integrated@meta.data$seurat_clusters == 10),"cell.types"] <- "OPCs"
sn_integrated@meta.data[which(sn_integrated@meta.data$seurat_clusters == 21),"cell.types"] <- "endothelial cells"
sn_integrated@meta.data[which(sn_integrated@meta.data$seurat_clusters == 24 |
                              sn_integrated@meta.data$seurat_clusters == 22 |
                              sn_integrated@meta.data$seurat_clusters == 17),"cell.types"] <- "pericytes+meningeal+Swchann cells"
sn_integrated@meta.data[which(sn_integrated@meta.data$seurat_clusters == 25),"cell.types"] <- "lymphocytes"
```

```{r}
# plots
p1 <- DimPlot(sn_integrated, reduction = "umap", group.by = "cell.types")
p2 <- DimPlot(sn_integrated, reduction = "umap", group.by = "seurat_clusters")
print(p1)
print(p2)
ggsave(paste0(saveDir, "/cellType_snRNA_Yadav.png"), plot = p1)
```

```{r}
saveRDS(sn_integrated, paste0(saveDir, "/snRNA_integratedCCA.rds"))
```
```{r}
sn_integrated <- readRDS(paste0(saveDir, "/snRNA_integratedCCA.rds"))
```




